import './globals.css'
import { Inter } from 'next/font/google'

import mmosertools,{isColor} from 'mmosertools';
 
console.log(mmosertools,'mmosertools')
  // const {isColor} = mmosertools;
  console.log(isColor,'iscolor')

// console.log('isColor #c6e48b:', isColor('#c6e48b')); // isColor #c6e48b: true



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'M Moser Knowledge Center',
  description: 'Generated by Celine Zhang',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
